apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  labels:
    app: fortio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
        - name: fortio
          image: fortio/fortio:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fortio
spec:
  type: NodePort
  selector:
    app: fortio
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
